# These are supported funding model platforms

# github: [laravel-seo-pro]
# patreon: laravel-seo-pro
# open_collective: laravel-seo-pro
# ko_fi: laravel-seo-pro
# tidelift: laravel-seo-pro
# custom: ['https://laravelseopro.com/donate']
