name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: dom, curl, libxml, mbstring, zip, pcntl, bcmath, soap, intl, gd, exif, iconv

    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache composer dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: composer-${{ hashFiles('composer.lock') }}
        restore-keys: composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run tests
      run: ./vendor/bin/phpunit

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          🚀 **Laravel SEO Pro ${{ github.ref_name }}**
          
          **Major Features:**
          - Complete Filament admin panel integration
          - SEO Dashboard, Sitemap Manager, Robots Manager
          - Advanced SEO features: breadcrumbs, scoring, optimization
          - Enhanced Livewire support with reactive components
          - Improved Blade components and directives
          
          **Technical Improvements:**
          - Modern PHP 8+ features and type safety
          - Fixed GitHub Actions workflows for Laravel packages
          - Better error handling and caching system
          - Comprehensive documentation and examples
          
          **Created by [mrdulal](https://github.com/mrdulal)**
        draft: false
        prerelease: false
